version: '3'

services:
  cart-api:
    build:
      context: ./_cart-api
      dockerfile: ./protected.Dockerfile
    ports:
      - "5050:5050"
    environment:
      - CARTAPI_SERVER_PORT=5050
      - INTERCEPTOR_PROTECTION_ENDPOINT=http://protection-api:5789/api/v1/validate
      - INTERCEPTOR_PROTECTION_TOKEN='token'
        # separated with ,
      - INTERCEPTOR_PROTECTION_CUSTOM_HEADERS=
        # separated with ,
      - INTERCEPTOR_PROTECTION_CUSTOM_COOKIES=
    depends_on:
      - protection-api
    networks:
      - interceptor

  web-app:
    image: web-app
    build:
      context: ./_web-app
    ports:
      - "3000:80"
    environment:
      - PORT=80
    networks:
      - interceptor
    depends_on:
      - cart-api

  protection-api:
    build:
      context: ./_protection-api
      dockerfile: ./Dockerfile
    ports:
      - "5789:5789"
    environment:
      - PROTECTIONAPI_SERVER_PORT=5789
      - PROTECTIONAPI_TOKENS=''
    networks:
      - interceptor

networks:
  interceptor:
    driver: bridge
